### PR TITLE
Show GIFs animated inline

### LINKED ISSUE #7: Inlined GIFs don't autoplay in teams
Because of this we have disabled inline GIFs in GifBot. If teams allows inlining to work just uncomment the lines after TODO:#7 and this will work

### PR DESCRIPTION
**Pull request by remyjette**
Resolves #7

### CODE REVIEW

**Comment by remyjette** [comment]
Turns out that if you set `TextFormat` to `xml`, it lets you put pretty much any HTML you want. Animated GIFs are not "officially supported", but they do work.

**Comment by alancast** [comment]
Looks fan-freaking-tastic! 2 things though:
1. Small one, removed the quotes around the reply text for the search query. I definitely think the message is better with them in (more clear what the search Giphy used was)
2. I think we should wait to do this until we have delete implemented

**Comment by remyjette** [comment]
Yeah, I'm fine with waiting to merge this until delete is implemented

**Review by alancast — APPROVED** [review]
lets wait for delete but looks good!

**Comment by alancast** [comment]
Decided to merge in as the final functionality add to the OG version of GifBot! Will update the readme after this

**Pull request merged**
